"""Initial migration

Revision ID: a7932866740e
Revises: 
Create Date: 2024-12-16 09:09:27.740714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7932866740e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('row',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jmeno', sa.String(length=100), nullable=False),
    sa.Column('vek', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('row')
    # ### end Alembic commands ###
